server:
  port: 8000
#  servlet:
#    context-path: /admin

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jinbi?useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
